version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: seeds_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Python/FastAPI Application
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
    name: seeds_db_data
